spring:
  application:
    name: pruebalegoback
  jackson:
    serialization:
      write-dates-as-timestamps: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/clinica_db
    username: postgres
    password: 1234
    pool:
      initial-size: 5
      max-size: 20
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

app:
  context: /api

weather:
  api:
    base-url: https://api.weather.gov
    timeout: 5000

logging:
  level:
    sura.pruebalegoback: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG